# Note: DO NOT use quantized model or quantization_bit when merging lora adapters

# model
model_name_or_path: saves/llava1_5-7b/full/sft_med
template: vicuna
finetuning_type: full
visual_inputs: true
cache_dir: ../hf_cache

# export
export_dir: models/llava1_5-7b-med
export_size: 2
export_device: cpu
export_legacy_format: false
export_hub_model_id: BUAADreamer/Chinese-LLaVA-Med-7B
hf_hub_token: xxxxx